// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpielmmD2WWOHHijjqNbmoAqdPglv83BY',
    appId: '1:1070089202147:web:c7619782719ebf490898d6',
    messagingSenderId: '1070089202147',
    projectId: 'fullqueso-menu',
    authDomain: 'fullqueso-menu.firebaseapp.com',
    databaseURL: 'https://fullqueso-menu-default-rtdb.firebaseio.com',
    storageBucket: 'fullqueso-menu.appspot.com',
    measurementId: 'G-42HC5JMB89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT7KB5LB9K72xW4Sh6hL_aaA0p59Wcmbw',
    appId: '1:1070089202147:android:d378f2fc14dbdcf10898d6',
    messagingSenderId: '1070089202147',
    projectId: 'fullqueso-menu',
    databaseURL: 'https://fullqueso-menu-default-rtdb.firebaseio.com',
    storageBucket: 'fullqueso-menu.appspot.com',
  );

}