List<Map<String, String>> bancos = [
  {'label': 'Banco de Venezuela', 'value': '0102'},
  {'label': 'Banco Provincial', 'value': '0108'},
  {'label': 'Banesco', 'value': '0134'},
  {'label': 'Banco Mercantil', 'value': '0105'},
  {'label': 'Banco Nacional de Crédito', 'value': '0191'},
  {'label': 'Bancamiga', 'value': '0172'},
  {'label': 'Banplus', 'value': '0174'},
  {'label': 'Banco Bicentenario', 'value': '0175'},
  {'label': 'Banco Plaza', 'value': '0138'},
  {'label': 'Banco del Caribe', 'value': '0114'},
  {'label': 'Banco Activo', 'value': '0171'},
  {'label': 'Banco Agrícola de Venezuela', 'value': '0166'},
  {'label': 'Banco Caroní', 'value': '0128'},
  {'label': 'Banco del Tesoro', 'value': '0163'},
  {'label': 'Banco de la Fuerza Armada Nacional', 'value': '0177'},
  {'label': 'Banco de la Gente Emprendedora', 'value': '0146'},
  {'label': 'Banco Exterior', 'value': '0115'},
  {'label': 'Banco Fondo Común', 'value': '0151'},
  {'label': 'Banco Internacional de Desarrollo', 'value': '0173'},
  {'label': 'Banco Sofitasa', 'value': '0137'},
  {'label': 'Banco Venezolano de Crédito', 'value': '0104'},
  {'label': 'Bancrecer', 'value': '0168'},
  {'label': 'Del Sur', 'value': '0157'},
  {'label': 'Mi Banco', 'value': '0169'},
  {'label': '100% Banco', 'value': '0156'},
  {'label': 'N58 Banco Digital, Banco Microfinanciero', 'value': '0178'},
  {'label': 'Instituto Municipal de Crédito Popular', 'value': '0601'},
];
